- hosts: 52.91.70.115
  tasks:
    - name: Stop and remove existing container
      docker_container:
        name: myfirstapp  # Update this if your container should have a different name
        state: absent

    - name: Start a new container
      docker_container:
        name: myfirstapp  # Ensure consistency with the Docker container name
        image: myfirstapp # Update to match the Docker image built in Jenkins
        state: started
        restart_policy: always

