pipeline {
    agent any
    stages {
        
        stage('Build Frontend') {
            steps {
                script {
                    sh 'docker build -t my-frontend-image app/frontend'
                }
            }
        }
        stage('Build Backend') {
            steps {
                script {
                    sh 'docker build -t my-frontend-image app/backend'
                }
            }
        }
        stage('Deploy Frontend') {
            steps {
                ansiblePlaybook(
                    playbook: 'ansible/deploy_frontend.yml',
                    inventory: 'inventory/hosts'
                )
            }
        }
        stage('Deploy Backend') {
            steps {
                ansiblePlaybook(
                    playbook: 'ansible/deploy_backend.yml',
                    inventory: 'inventory/hosts'
                )
            }
        }
    }
}

